name = "BATsDistribution"
uuid = "6bd37c0a-d4fd-4ef6-9e65-cd3b634e9aab"
authors = ["Mitchell Krock <mk1867@stat.rutgers.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
Roots = "1"
